#!/bin/bash
#
# Used by Travis to submit named assets to the correct environments.

set -euo pipefail

PUBLISH="false"

if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
  case ${TRAVIS_BRANCH} in
    master)
      echo "Submitting to staging."
      export CONTENT_STORE_URL=https://staging.developer.rackspace.com:9000/
      export CONTENT_STORE_APIKEY=${KEY1}${KEY2}${KEY3}
      export NODE_TLS_REJECT_UNAUTHORIZED=0
      export PUBLISH="true"
      ;;
    *)
      echo "Not submitting ${TRAVIS_BRANCH} anywhere."
      ;;
  esac
else
  echo "Not submitting pull request build anywhere."
fi

if [ "${PUBLISH}" = "true" ]; then
  npm install
  grunt build
fi
